name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 22
          repo-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      - run: sbt test